accounts/urls.py
from django.urls import path
from . import views

app_name = 'account_app'
urlpatterns = [
    path('register/', views.RegisterClassBaseView.as_view(), name='register'),
    path('login/', views.LoginClassBaseView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('dashboard/', views.DashboardClassBaseView.as_view(), name='dashboard'),
    path('', views.DashboardClassBaseView.as_view(), name='dashboard'),
    path('forgot/password/', views.ForgotPasswordClassBaseView.as_view(), name='forgot_p'),
    path('reset/password/validate/<uidb64>/<token>/', views.ResetPasswordValidate.as_view(),
         name='reset_password_validate'),
    path('reset/password', views.ResetPassword.as_view(), name='reset_password'),
    path('my_orders/', views.MyOrdersView.as_view(), name='my_orders'),
    path('edit/profile', views.EditProfileView.as_view(), name='edit_profile'),
    path('change/password', views.ChangePasswordView.as_view(), name='change_password'),
    path('my/orders/detail/<int:order_number>/', views.MyOrdersDetail.as_view(), name='my_orders_detail'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart_app'
urlpatterns = [
    path('', views.ProductCartView.as_view(), name='product_cart'),
    path('add/<int:product_id>/', views.AddCartView.as_view(), name='add_to_cart'),
    path('product/decrease/<str:unique_id>/', views.decrease_added_product, name='product_decrease'),
    path('product/Remove/<str:unique_id>/', views.remove_cart_view, name='product_remove'),
    path('Checkout/', views.CheckoutView.as_view(), name='checkout'),

]

d_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include  # Correct import statements
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
                  path('درگاه_امن/', admin.site.urls),
                  path('', views.home, name='home'),  # Root URL mapped to home view
                  path('product/', include('store.urls')),  # Including store.urls for product
                  path('cart/', include('cart.urls')),  # Including cart.urls for cart
                  path('account/', include('accounts.urls')),  # Including account.urls for register and login etc .
                  path('order/', include('orders.urls')),
                  path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Serving media files

store/urls.py
from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('', viewset=views.ProductvViewsets)

app_name = 'store_app'
urlpatterns = [
    path('all/', views.ProductsPageView.as_view(), name='products_page'),
    path('search/', views.SearchClassBaseView.as_view(), name='search'),
    path('category/<slug:slug>/', views.ProductsPageView.as_view(), name='products_by_category'),
    path('detail/<slug:slug>', views.ProductDetailView.as_view(), name='product_detail'),
    path('viewset/products', include(router.urls), name='view_set'),
    path('review/submit/<int:product_id>/', views.ReviewSumitView.as_view(), name='review_submit')
]

templates/includes/alert_message.html
{% if messages %}
    {% for message in messages %}
        <div class="message container">
            <div class="alert alert-{{ message.tags|default:'info' }} alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>


                {% if message.level == 'error' %}Error:{% endif %}
                {{ message }}

            </div>
        </div>
    {% endfor %}
{% endif %}

templates/includes/dashboard_sidebar.html
<aside class="col-md-3">
    <!--   SIDEBAR   -->
    <ul class="list-group">
        <a class="list-group-item {% if '/account/' == request.path %} active {% endif %}"
           href="{% url 'account_app:dashboard' %}"> Dashboard </a>
        <a class="list-group-item {% if '/account/my_orders/' == request.path %}active{% endif %}"
           href="{% url 'account_app:my_orders' %}"> My order history </a>
        <a class="list-group-item {% if '/account/edit/profile' == request.path %} active {% endif %}"
           href="{% url 'account_app:edit_profile' %}"> Edit profile </a>
        <a class="list-group-item {% if '/account/change/password' == request.path %}active{% endif %}"
           href="{% url 'account_app:change_password' %}"> Change Password </a>
    </ul>
    <br>
    <a class="btn btn-light btn-block" href="{% url 'account_app:logout' %}"> <i class="fa fa-power-off"></i> <span
            class="text">Log out</span>
    </a>
    <!--   SIDEBAR .//END   -->
</aside>

templates/includes/footer.html
<footer class="section-footer border-top">
    <div class="container">
        <section class="footer-bottom border-top row">
            <div class="col-md-2">
                <p class="text-muted"> &copy 2019 Company name </p>
            </div>
            <div class="col-md-8 text-md-center">
                <span class="px-2">info@pixsellz.io</span>
                <span class="px-2">+879-332-9375</span>
                <span class="px-2">Street name 123, Avanue abc</span>
            </div>
            <div class="col-md-2 text-md-right text-muted">
                <i class="fab fa-lg fa-cc-visa"></i>
                <i class="fab fa-lg fa-cc-paypal"></i>
                <i class="fab fa-lg fa-cc-mastercard"></i>
            </div>
        </section>
    </div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $('.thumb a').click(function (e) {
            e.preventDefault();
            $('.mainImage').attr('src', $(this).attr('href'));
        });
    });
</script>


</body>
</html>

templates/includes/navbar.html
{% load static %}


<header class="section-header">
    <nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTop4">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link"> English </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link"> USD </a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
                    <li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
                </ul> <!-- list-inline //  -->
            </div> <!-- navbar-collapse .// -->
        </div> <!-- container //  -->
    </nav>

    <section class="header-main border-bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-2 col-md-3 col-6">
                    <a href="{% url 'home' %}" class="brand-wrap">
                        <img class="logo" src="{% static 'images/logo.png' %}">
                    </a> <!-- brand-wrap.// -->
                </div>
                <div class="col-lg col-sm col-md col-6 flex-grow-0">
                    <div class="category-wrap dropdown d-inline-block float-right">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bars"></i> All category
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'store_app:products_page' %}"> All products </a>
                            {% for category in cat_li %}
                                <a class="dropdown-item" href="{{ category.get_url }}">{{ category.category_name }} </a>
                            {% endfor %}

                        </div>
                    </div>  <!-- category-wrap.// -->
                </div> <!-- col.// -->

                <a href="{% url 'store_app:products_page' %}" class="btn btn-outline-primary">Store</a>
                <div class="col-lg  col-md-6 col-sm-12 col">
                    <form action="{% url 'store_app:search' %}" class="search" method="post">
                        {% csrf_token %}
                        <div class="input-group w-100">
                            <input name="keyword" type="text" class="form-control" style="width:60%;"
                                   placeholder="Search">

                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form> <!-- search-wrap .end// -->
                </div> <!-- col.// -->

                <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                    <div class="d-flex justify-content-end mb-3 mb-lg-0">
                        {% if user.id is None %}
                            <div class="widget-header">
                                <small class="title text-muted">Welcome guest!</small>
                                <div>
                                    <a href="{% url 'account_app:login' %}">Sign in</a> <span
                                        class="dark-transp"> | </span>
                                    <a href="{% url 'account_app:register' %}"> Register</a>
                                </div>
                            </div>
                        {% else %}
                            <div class="widget-header">
                                <small class="title text-muted">Welcome {{ user.email }}</small>
                                <div>
                                    <a href="{% url 'account_app:dashboard' %}">Dashboard</a> <span
                                        class="dark-transp"> | </span>
                                    <a href="{% url 'account_app:logout' %}"> Logout</a>
                                </div>
                            </div>
                        {% endif %}
                        <a href="{% url 'cart_app:product_cart' %}" class="widget-header pl-3 ml-3">
                            <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                            <span class="badge badge-pill badge-danger notify">{{ cart_count }}</span>
                        </a>
                    </div> <!-- widgets-wrap.// -->
                </div> <!-- col.// -->
            </div> <!-- row.// -->
        </div> <!-- container.// -->
    </section> <!-- header-main .// -->


</header> <!-- section-header.// -->


<!-- ========================= SECTION MAIN ========================= -->
<section class="section-intro padding-y-sm">
    <div class="container">

        <div class="intro-banner-wrap">
            <img src="{% static 'images/banners/1.jpg' %}" class="img-fluid rounded">
        </div>

    </div> <!-- container //  -->
</section>
<!-- ========================= SECTION MAIN END// ========================= -->

<!-- ========================= SECTION  ========================= -->
<section class="section-name padding-y-sm">
    <div class="container">

        <header class="section-heading">
            {% if request.path == '/' %}

            {% else %}
                <a href="{% url 'home' %}" class="btn btn-outline-primary float-right">Back Home</a>
            {% endif %}
            <h3 class="section-title">{{ request.path|cut:'/' }}</h3>


        </header><!-- sect-heading -->