accounts/urls.py
from django.urls import path
from . import views

app_name = 'account_app'
urlpatterns = [
    path('register/', views.RegisterClassBaseView.as_view(), name='register'),
    path('login/', views.LoginClassBaseView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('dashboard/', views.DashboardClassBaseView.as_view(), name='dashboard'),
    path('', views.DashboardClassBaseView.as_view(), name='dashboard'),
    path('forgot/password/', views.ForgotPasswordClassBaseView.as_view(), name='forgot_p'),
    path('reset/password/validate/<uidb64>/<token>/', views.ResetPasswordValidate.as_view(),
         name='reset_password_validate'),
    path('reset/password', views.ResetPassword.as_view(), name='reset_password'),
    path('my_orders/', views.MyOrdersView.as_view(), name='my_orders'),
    path('edit/profile', views.EditProfileView.as_view(), name='edit_profile'),
    path('change/password', views.ChangePasswordView.as_view(), name='change_password'),
    path('my/orders/detail/<int:order_number>/', views.MyOrdersDetail.as_view(), name='my_orders_detail'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart_app'
urlpatterns = [
    path('', views.ProductCartView.as_view(), name='product_cart'),
    path('add/<int:product_id>/', views.AddCartView.as_view(), name='add_to_cart'),
    path('product/decrease/<str:unique_id>/', views.decrease_added_product, name='product_decrease'),
    path('product/Remove/<str:unique_id>/', views.remove_cart_view, name='product_remove'),
    path('Checkout/', views.CheckoutView.as_view(), name='checkout'),

]

d_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include  # Correct import statements
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
                  path('درگاه_امن/', admin.site.urls),
                  path('', views.home, name='home'),  # Root URL mapped to home view
                  path('product/', include('store.urls')),  # Including store.urls for product
                  path('cart/', include('cart.urls')),  # Including cart.urls for cart
                  path('account/', include('accounts.urls')),  # Including account.urls for register and login etc .
                  path('order/', include('orders.urls')),
                  path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Serving media files

orders/urls.py
from django.urls import path
from . import views

app_name = 'order_app'
urlpatterns = [
    path('place_order/', views.PlaceOrderView.as_view(), name='place_order'),
    path('payment/', views.payments, name='payment'),
    path('complete', views.order_complete, name='order_complete'),
]

store/urls.py
from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('', viewset=views.ProductvViewsets)

app_name = 'store_app'
urlpatterns = [
    path('all/', views.ProductsPageView.as_view(), name='products_page'),
    path('search/', views.SearchClassBaseView.as_view(), name='search'),
    path('category/<slug:slug>/', views.ProductsPageView.as_view(), name='products_by_category'),
    path('detail/<slug:slug>', views.ProductDetailView.as_view(), name='product_detail'),
    path('viewset/products', include(router.urls), name='view_set'),
    path('review/submit/<int:product_id>/', views.ReviewSumitView.as_view(), name='review_submit')
]

cart/models.py
from django.db import models
from accounts.models import Account
from store.models import Product, Variation
import uuid


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, unique=True, blank=True)
    created = models.DateField('created at', auto_now_add=True)

    def __str__(self):
        return self.cart_id

    def save(self, *args, **kwargs):
        if not self.cart_id:
            self.cart_id = str(uuid.uuid4())  # Generate unique cart_id
        super().save(*args, **kwargs)


class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='cartitem')
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='cartitem', null=True)
    variations = models.ManyToManyField(Variation, blank=True)
    quantity = models.PositiveIntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product.name

store/models.py
from django.db import models

from accounts.models import Account
from category.models import Category
from decimal import Decimal, ROUND_HALF_UP
from django.db.models import Avg, Count


class Product(models.Model):
    """
    Represents a product in the inventory, including details such as name,
    description, price, stock, and category.
    """
    name = models.CharField(max_length=30, verbose_name="Product Name")
    title = models.CharField(max_length=70, verbose_name="Product Title")
    slug = models.SlugField(verbose_name="Product Slug")
    description = models.TextField('Long Description')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Product Price")
    discount = models.IntegerField('Product Discount', blank=True, null=True)
    image = models.ImageField(upload_to='photos/product', verbose_name="Product Image")
    stock = models.PositiveIntegerField('Remaining in Stock')
    available = models.BooleanField('Is Available in Stock', default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Product Category")
    created = models.DateTimeField('Created at', auto_now_add=True)
    modified = models.DateTimeField('Modified at', auto_now=True)

    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count

    def __str__(self):
        return self.name

    def get_discounted_price(self):
        # Ensure the discount is not None and is a valid percentage
        if self.discount is not None:
            # Convert discount percentage to Decimal and calculate discount factor
            discount_percent = Decimal(self.discount) / Decimal(100)
            discount_factor = Decimal(1) - discount_percent

            # Calculate discounted price
            discounted_price = self.price * discount_factor

            # Return the discounted price rounded to 2 decimal places
            return discounted_price.quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)

        # If no discount, return the original price
        return self.price


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)


variation_category_choice = (
    ('color', 'Color'),
    ('size', 'Size'),
)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=30, choices=variation_category_choice,
                                          verbose_name="Product Variation Category")
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField('Created at', auto_now_add=True)
    objects = VariationManager()

    def __str__(self):
        return self.variation_value


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class ProductGallery(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='galleries')
    image = models.ImageField(upload_to='galleries', verbose_name="Product Image")

    class Meta:
        verbose_name = 'Product Gallery'
        verbose_name_plural = 'Product Galleries'

    def __str__(self):
        return self.product.name

store/forms.py
from django import forms
from .models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

cart/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View

from orders.models import Order
from store.models import Product, Variation
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.mixins import LoginRequiredMixin


# region Cart view

class ProductCartView(View):
    def get(self, request, total=0, quantity=0, cart_items=None):
        tax = 0
        grand_total = 0
        try:
            if request.user.is_authenticated:
                cart_items = CartItem.objects.filter(user=request.user, is_active=True)
            else:
                cart = Cart.objects.get(cart_id=_cart_id(request))
                cart_items = CartItem.objects.filter(cart=cart, is_active=True)
            for item in cart_items:
                total += (item.product.price * item.quantity)
                quantity += item.quantity
            tax = (2 * total) / 100
            grand_total = total + tax
        except ObjectDoesNotExist:
            cart_items = []

        context = {
            "total": total,
            "quantity": quantity,
            "items": cart_items,
            "tax": tax,
            "grand_total": grand_total
        }
        return render(request, 'store/cart.html', context)


# endregion


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


# region decrease and remove cart item

def decrease_added_product(request, unique_id):
    try:
        # Get the single cart item object instead of a QuerySet
        cart_item = CartItem.objects.get(unique_id=unique_id)
        if cart_item.quantity <= 1:
            cart_item.delete()
        else:
            cart_item.quantity -= 1
            cart_item.save()
    except CartItem.DoesNotExist:
        pass
    return redirect('cart_app:product_cart')


def remove_cart_view(request, unique_id):
    try:
        cart_item = CartItem.objects.get(unique_id=unique_id)
        cart_item.delete()
    except CartItem.DoesNotExist:
        pass

    return redirect('cart_app:product_cart')


# endregion


# region  Cart logic

class AddCartView(View):
    def get(self, request, product_id):
        current_user = request.user
        product = Product.objects.get(id=product_id)  # Get the product

        # Retrieve product variations from request
        product_variation = []
        for item in request.GET:
            key = item
            value = request.GET[key]
            try:
                variation = Variation.objects.get(product=product, variation_category__iexact=key,
                                                  variation_value__iexact=value)
                product_variation.append(variation)
            except Variation.DoesNotExist:
                pass

        # If the user is authenticated
        if current_user.is_authenticated:
            return self.handle_cart_for_authenticated_user(request, product, product_variation, current_user)
        else:
            return self.handle_cart_for_unauthenticated_user(request, product, product_variation)

    def handle_cart_for_authenticated_user(self, request, product, product_variation, user):
        cart_items = CartItem.objects.filter(product=product, user=user)

        if cart_items.exists():
            return self.update_or_create_cart_item(cart_items, product_variation, product, user=user)
        else:
            return self.create_cart_item(product, product_variation, user=user)

    def handle_cart_for_unauthenticated_user(self, request, product, product_variation):
        cart_id = _cart_id(request)
        cart, created = Cart.objects.get_or_create(cart_id=cart_id)
        cart_items = CartItem.objects.filter(product=product, cart=cart)

        if cart_items.exists():
            return self.update_or_create_cart_item(cart_items, product_variation, product, cart=cart)
        else:
            return self.create_cart_item(product, product_variation, cart=cart)

    def update_or_create_cart_item(self, cart_items, product_variation, product, user=None, cart=None):
        ex_var_list = []
        id_list = []

        # Prepare existing variations and their cart item IDs
        for item in cart_items:
            existing_variations = list(item.variations.all())
            ex_var_list.append(existing_variations)
            id_list.append(item.id)

        if product_variation in ex_var_list:
            # If variations match, increase quantity
            index = ex_var_list.index(product_variation)
            item_id = id_list[index]
            item = CartItem.objects.get(id=item_id)
            item.quantity += 1
            item.save()
        else:
            # Create a new cart item if variations don't match
            item = CartItem.objects.create(product=product, quantity=1, user=user, cart=cart)
            if product_variation:
                item.variations.add(*product_variation)
            item.save()

        return redirect('cart_app:product_cart')

    def create_cart_item(self, product, product_variation, user=None, cart=None):
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            user=user,
            cart=cart,
        )
        if product_variation:
            cart_item.variations.add(*product_variation)
        cart_item.save()

        return redirect('cart_app:product_cart')

    def remove_cart(request, product_id, cart_item_id):

        product = get_object_or_404(Product, id=product_id)
        try:
            if request.user.is_authenticated:
                cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
            else:
                cart = Cart.objects.get(cart_id=_cart_id(request))
                cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
            if cart_item.quantity > 1:
                cart_item.quantity -= 1
                cart_item.save()
            else:
                cart_item.delete()
        except:
            pass
        return redirect('cart_app:product_cart')


# endregion


# region Checkout


class CheckoutView(LoginRequiredMixin, View):
    login_url = 'account_app:login'

    def get(self, request, total=0, quantity=0, cart_items=None):
        try:
            tax = 0
            grand_total = 0
            if request.user.is_authenticated:
                cart_items = CartItem.objects.filter(user=request.user, is_active=True)
            else:
                cart = Cart.objects.get(cart_id=_cart_id(request))
                cart_items = CartItem.objects.filter(cart=cart, is_active=True)

            for cart_item in cart_items:
                total += (cart_item.product.price * cart_item.quantity)
                quantity += cart_item.quantity

            tax = (2 * total) / 100
            grand_total = total + tax

        except ObjectDoesNotExist:
            # Handle the case where the cart or cart items do not exist
            cart_items = []

        context = {
            "total": total,
            "quantity": quantity,
            "cart_items": cart_items,
            "tax": tax,
            "grand_total": grand_total
        }

        return render(request, 'store/checkout.html', context)

# end region

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <section class="section-content padding-y bg">
        <div class="container">

            <!-- ============================ COMPONENT 1 ================================= -->

            {% if not items %}

                <h2 class='text-center'>
                    your shopping cart is emty
                </h2>
                <div class="text-center">
                    <a href="{% url 'store_app:products_page' %}" class="btn btn-primary">countinue shopping</a>
                </div>

            {% else %}

                <div class="row">
                    <aside class="col-lg-9">
                        <div class="card">
                            <table class="table table-borderless table-shopping-cart">
                                <thead class="text-muted">
                                <tr class="small text-uppercase">
                                    <th scope="col">Product</th>
                                    <th scope="col" width="120">Quantity</th>
                                    <th scope="col" width="120">Price</th>
                                    <th scope="col" class="text-right" width="200"></th>
                                </tr>
                                </thead>
                                <tbody>

                                {% for item in items %}
                                    <tr>
                                        <td>
                                            <figure class="itemside align-items-center">
                                                <div class="aside"><img src="{{ item.product.image.url }}"
                                                                        class="img-sm"></div>
                                                <figcaption class="info">
                                                    <a href="{% url 'store_app:product_detail' item.product.slug %}"
                                                       class="title text-dark">{{ item.product.name }}</a>
                                                    {% if item.variations.exists %}
                                                        {% for variation in item.variations.all %}
                                                            <p class="text-muted small">{{ variation.variation_category }}: {{ variation.variation_value }}
                                                                <br>
                                                            </p>
                                                        {% endfor %}
                                                    {% endif %}
                                                </figcaption>
                                            </figure>
                                        </td>
                                        <td>
                                            <div class="col">
                                                <div class="input-group input-spinner">
                                                    <div class="input-group-prepend">
                                                        <a href="{% url 'cart_app:product_decrease' item.unique_id %}"
                                                           class="btn btn-light">
                                                            <i class="fa fa-minus"></i>
                                                        </a>
                                                    </div>
                                                    <input type="text" class="form-control" value="{{ item.quantity }}">
                                                    <div class="input-group-append">
                                                        <form action="{% url 'cart_app:add_to_cart' item.product.id %}"
                                                              method="GET">
                                                            {% for variation in item.variations.all %}
                                                                <input type="hidden"
                                                                       name="{{ variation.variation_category|lower }}"
                                                                       value="{{ variation.variation_value|capfirst }}">
                                                            {% endfor %}
                                                            <button class="btn btn-light" type="submit"
                                                                    id="button-plus">
                                                                <i class="fa fa-plus"></i>
                                                            </button>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="price-wrap">
                                                <var class="price">${{ item.sub_total }}</var>
                                                <small class="text-muted">${{ item.product.get_discounted_price }}
                                                    each</small>
                                            </div>
                                        </td>
                                        <td class="text-right">
                                            <a href="{% url 'cart_app:product_remove' item.unique_id %}"
                                               class="btn btn-danger">Remove</a>
                                        </td>
                                    </tr>
                                {% endfor %}


                                </tbody>
                            </table>

                        </div> <!-- card.// -->

                    </aside> <!-- col.// -->
                    <aside class="col-lg-3">

                        <div class="card">
                            <div class="card-body">
                                <dl class="dlist-align">
                                    <dt>Total price:</dt>
                                    <dd class="text-right">${{ total }}</dd>
                                </dl>
                                <dl class="dlist-align">
                                    <dt>Tax:</dt>
                                    <dd class="text-right"> ${{ tax }}</dd>
                                </dl>
                                <dl class="dlist-align">
                                    <dt>Total:</dt>
                                    <dd class="text-right text-dark b"><strong>${{ grand_total }}</strong></dd>
                                </dl>
                                <hr>
                                <p class="text-center mb-3">
                                    <img src="{% static 'images/misc/payments.png' %}" height="26">
                                </p>
                                <a href="{% url 'cart_app:checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
                                <a href="{% url 'store_app:products_page' %}" class="btn btn-light btn-block">Continue
                                    Shopping</a>
                            </div> <!-- card-body.// -->
                        </div> <!-- card.// -->

                    </aside> <!-- col.// -->


                </div> <!-- row.// -->

            {% endif %}
            <!-- ============================ COMPONENT 1 END .// ================================= -->

        </div> <!-- container .//  -->
    </section>

{% endblock %}

templates/store/products_page.html
{% extends 'base.html' %}
{% load static %}



{% block content %}

<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
<div class="container">
	<h2 class="title-page">Our Store</h2>

</div> <!-- container //  -->
</section>

<style>
.active-category {
    font-weight: bold;
    color: #ff5722; /* Example color */
}
</style>

<!-- ========================= SECTION INTRO END// ========================= -->

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
<div class="container">

<div class="row">
	<aside class="col-md-3">

<div class="card">
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Categories</h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_1" style="">
    <div class="card-body">
        <ul class="list-menu">
            <li>
                <a href="{% url 'store_app:products_page' %}"
                   {% if not request.path|slice:'-1' and request.path == '/product/all/' %}
                       class="active-category"
                   {% endif %}>
                   All products
                </a>
            </li>
            {% for category in cat_li %}
                <li>
                    <a href="{{ category.get_url }}"
                       {% if request.path == category.get_url %}
                           class="active-category"
                       {% endif %}>
                        {{ category.category_name }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div> <!-- card-body.// -->
</div>

	</article> <!-- filter-group  .// -->
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_4" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Sizes </h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_4" style="">
			<div class="card-body">
			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> XS </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> SM </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> LG </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> XXL </span>
			  </label>
		</div><!-- card-body.// -->
		</div>
	</article> <!-- filter-group .// -->

	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Price range </h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_3" style="">
			<div class="card-body">

				<div class="form-row">
				<div class="form-group col-md-6">
				  <label>Min</label>
				  <!-- <input class="form-control" placeholder="$0" type="number"> -->
				  	<select class="mr-2 form-control">
						<option value="0">$0</option>
						<option value="50">$50</option>
						<option value="100">$100</option>
						<option value="150">$150</option>
						<option value="200">$200</option>
						<option value="500">$500</option>
						<option value="1000">$1000</option>
					</select>
				</div>
				<div class="form-group text-right col-md-6">
				  <label>Max</label>
				  	<select class="mr-2 form-control">
						<option value="50">$50</option>
						<option value="100">$100</option>
						<option value="150">$150</option>
						<option value="200">$200</option>
						<option value="500">$500</option>
						<option value="1000">$1000</option>
						<option value="2000">$2000+</option>
					</select>
				</div>
				</div> <!-- form-row.// -->
				<button class="btn btn-block btn-primary">Apply</button>
			</div><!-- card-body.// -->
		</div>
	</article> <!-- filter-group .// -->

</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<main class="col-md-9">

<header class="border-bottom mb-4 pb-3">
		<div class="form-inline">
			<span class="mr-md-auto">{{ products_count }} Items found </span>

		</div>
</header><!-- sect-heading -->

<div class="row">


	{% for product in products %}
	<div class="col-md-4">
	    <figure class="card card-product-grid">
	        <div class="img-wrap">
	            <!-- Replace the static image path with the dynamic product image URL -->
	            <img src="{{ product.image.url }}" alt="{{ product.name }}">
	        </div> <!-- img-wrap.// -->
	        <figcaption class="info-wrap">
	            <div class="fix-height">
	                <!-- Replace the static title with the product's name -->
	                <a href="{% url 'store_app:product_detail' product.slug %}" class="title">{{ product.name }}</a>
	                <div class="price-wrap mt-2">
	                    <!-- Replace the static price with the product's price -->
	                    <!-- Optional: Show the old price if available -->
	                    {% if product.discount %}
	                    <del class="price-old">${{ product.price }}</del>
											<span class="price">${{ product.get_discounted_price }}</span>
											{% else %}
											<span class="price">${{ product.price }}</span>
	                    {% endif %}
	                </div> <!-- price-wrap.// -->
	            </div>
	            <!-- Update the button text dynamically if needed -->
	            <a href="{% url 'store_app:product_detail' slug=product.slug  %}" class="btn btn-block btn-primary">View  Detail</a>
	        </figcaption>
	    </figure>
	</div> <!-- col.// -->
	{% endfor %}



</div> <!-- row end.// -->


<nav class="mt-4" aria-label="Page navigation sample">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a></li>
    {% endif %}

    {% for page in page_obj.paginator.page_range %}
      {% if page == page_obj.number %}
        <li class="page-item active"><a class="page-link">{{ page }}</a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
    {% endif %}
  </ul>
</nav>


	</main> <!-- col.// -->

</div>

</div> <!-- container .//  -->
</section>

{% endblock %}


<!-- ========================= FOOTER ========================= -->